version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: time_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: TimeRegDb
      MYSQL_USER: app
      MYSQL_PASSWORD: apppass
    command: --default-authentication-plugin=caching_sha2_password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpass"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: time_backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=db;Port=3306;Database=TimeRegDb;User=app;Password=apppass;TreatTinyAsBoolean=false;AllowPublicKeyRetrieval=true;SslMode=None"
    ports:
      - "5196:5196"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: "http://backend:5196/"
    container_name: time_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  dbdata:
